
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrtgkvpbptxueetuqlmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpydGdrdnBicHR4dWVldHVxbG1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NDk5NjMsImV4cCI6MjA2MDMyNTk2M30.kdpI-0IZ8V2xVU-du10qCI3sshFUSDaIZaN_oRry7nU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
